import {
  NgoPartner,
  HealthCamp,
  CampAttendee,
  CharityGrant,
  NgoFundTransaction
} from '../types';

export const DEFAULT_NGO_PARTNERS: NgoPartner[] = [
  {
    id: 'ngo_rotary_3291',
    ngoCode: 'NGO-ROTARY-3291',
    name: 'Rotary Club Healthcare & Rural Relief Foundation',
    category: 'rotary_lions',
    registrationNumber: 'TR/WB/2012/88129',
    taxExemption80G: 'AAATR8812E20211',
    taxExemption12A: '12A-CIT-KOL-8812',
    contactPerson: 'Mr. Arvind Roy',
    designation: 'Welfare Director & Trustee',
    phone: '+91 98310 99221',
    email: 'rotary3291.healthcare@rotaryrelief.org',
    address: 'Rotary Sadan, 94/2 Chowringhee Road, Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    logoUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=200&auto=format&fit=crop&q=80',
    mouSignedDate: '2025-01-15',
    mouValidTill: '2028-01-14',
    mouScope: '100% Free Rural Cardiology, ECG, Blood Sugar Camps & BPL Senior Citizen Subsidized Diagnostic Treatments.',
    totalGrantDeposited: 350000,
    totalAidDisbursed: 108500,
    activeBalance: 241500,
    status: 'active',
    coBrandedCardEnabled: true,
    coBrandCardPrefix: 'ROTARY-SEVA',
    defaultDiscountPercent: 100,
    notes: 'Standing partnership for monthly rural village health camps and emergency dialysis subsidies.',
    createdAt: '2025-01-15T09:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'ngo_lions_greater',
    ngoCode: 'NGO-LIONS-088',
    name: 'Lions Club International Eye & Diabetes Care Mission',
    category: 'rotary_lions',
    registrationNumber: 'LN/WB/2015/44192',
    taxExemption80G: 'AAATL4419L20198',
    taxExemption12A: '12A-CIT-HOW-4419',
    contactPerson: 'Dr. Meenakshi Sengupta',
    designation: 'Chief Medical Coordinator',
    phone: '+91 98301 44882',
    email: 'lions.service@lionscarefoundation.org',
    address: 'Lions Seva Kendra, 12 GT Road, Howrah',
    district: 'Howrah',
    state: 'West Bengal',
    logoUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=200&auto=format&fit=crop&q=80',
    mouSignedDate: '2025-03-01',
    mouValidTill: '2027-02-28',
    mouScope: 'Free Eye Cataract Screenings, Glaucoma, HbA1c testing, and spectacle distribution for underprivileged seniors.',
    totalGrantDeposited: 250000,
    totalAidDisbursed: 78000,
    activeBalance: 172000,
    status: 'active',
    coBrandedCardEnabled: true,
    coBrandCardPrefix: 'LIONS-VISION',
    defaultDiscountPercent: 100,
    notes: 'Co-sponsor for bi-weekly ophthalmology and diabetes camps in peri-urban areas.',
    createdAt: '2025-03-01T10:30:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'ngo_tata_csr',
    ngoCode: 'CSR-TATA-EAST',
    name: 'Tata Corporate CSR Social Health & Oncology Aid Trust',
    category: 'corporate_csr',
    registrationNumber: 'CSR/MH/2019/77210',
    taxExemption80G: 'AAATT7721C20223',
    taxExemption12A: '12A-CIT-MUM-7721',
    contactPerson: 'Mr. Rajeshwar Ghosh',
    designation: 'Head of CSR Initiatives (East)',
    phone: '+91 98305 11099',
    email: 'csr.health@tatarelief.org',
    address: 'Tata Centre, 43 Jawaharlal Nehru Road, Kolkata',
    district: 'Kolkata',
    state: 'West Bengal',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=200&auto=format&fit=crop&q=80',
    mouSignedDate: '2025-02-10',
    mouValidTill: '2028-02-09',
    mouScope: 'Full grant coverage for critical cancer lab diagnostics, dialysis sessions, MRI/CT aid for families below poverty line (BPL).',
    totalGrantDeposited: 600000,
    totalAidDisbursed: 185000,
    activeBalance: 415000,
    status: 'active',
    coBrandedCardEnabled: true,
    coBrandCardPrefix: 'TATA-AROGYA',
    defaultDiscountPercent: 100,
    notes: 'Major corporate grant partner providing emergency procedure relief and high-cost lab test subsidies.',
    createdAt: '2025-02-10T11:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'ngo_bharat_seva',
    ngoCode: 'NGO-BHARAT-04',
    name: 'Bharat Arogya Seva Mission (Maternal & Child Relief)',
    category: 'charity_trust',
    registrationNumber: 'SOC/WB/2018/10928',
    taxExemption80G: 'AATNB1092B20202',
    taxExemption12A: '12A-CIT-KOL-1092',
    contactPerson: 'Smt. Shrabani Majumdar',
    designation: 'General Secretary',
    phone: '+91 98319 88344',
    email: 'info@bharatarogyamission.org',
    address: 'Panchayat Road, Baruipur, South 24 Parganas',
    district: 'South 24 Parganas',
    state: 'West Bengal',
    logoUrl: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=200&auto=format&fit=crop&q=80',
    mouSignedDate: '2025-04-01',
    mouValidTill: '2027-03-31',
    mouScope: 'Maternal health packages, pediatric malnutrition blood workups, and anemia screening for rural girls.',
    totalGrantDeposited: 200000,
    totalAidDisbursed: 64200,
    activeBalance: 135800,
    status: 'active',
    coBrandedCardEnabled: true,
    coBrandCardPrefix: 'BHARAT-MATRI',
    defaultDiscountPercent: 100,
    notes: 'Active in coastal and riverine blocks for doorstep maternal blood investigations.',
    createdAt: '2025-04-01T08:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  }
];

export const DEFAULT_HEALTH_CAMPS: HealthCamp[] = [
  {
    id: 'camp_sonarpur_2026_01',
    campCode: 'CAMP-2026-081',
    title: 'Free Rural Diabetes, Cardiac & Blood Sugar Screening Camp',
    ngoPartnerId: 'ngo_rotary_3291',
    ngoPartnerName: 'Rotary Club Healthcare & Rural Relief Foundation',
    category: 'diabetes_cardiac',
    campDate: '2026-09-05',
    startTime: '09:00',
    endTime: '15:00',
    venueName: 'Sonarpur Gram Panchayat Community Hall',
    locationAddress: 'Station Road, Sonarpur, South 24 Parganas',
    villageOrPanchayat: 'Sonarpur Gram Panchayat',
    district: 'South 24 Parganas',
    assignedDoctorIds: ['doc_001', 'doc_002'],
    assignedDoctorNames: ['Dr. Subhashish Roy (MD Cardiology)', 'Dr. Priyadarshini Sen (MD General Medicine)'],
    coordinatorName: 'Arup Biswas',
    coordinatorPhone: '+91 98311 22334',
    targetBeneficiaries: 150,
    registeredCount: 142,
    attendedCount: 128,
    testsConductedCount: 384,
    freeCardsIssuedCount: 88,
    allocatedBudget: 25000,
    actualSpent: 21800,
    status: 'active_today',
    freeServicesOffered: [
      'Random Blood Sugar (RBS)',
      '12-Lead ECG Screening',
      'Blood Pressure & Vitals Check',
      'BMI & Lipid Risk Assessment',
      'Free Physician Consultation',
      'Essential Cardiac & BP Starter Meds'
    ],
    summaryNotes: 'High community turnout in the morning session. 22 patients identified with undiagnosed Grade II hypertension and referred for full lab lipid panels.',
    createdAt: '2026-08-20T10:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  },
  {
    id: 'camp_howrah_eye_2026_02',
    campCode: 'CAMP-2026-074',
    title: 'Senior Citizen Cataract, Glaucoma & Vision Screening Camp',
    ngoPartnerId: 'ngo_lions_greater',
    ngoPartnerName: 'Lions Club International Eye & Diabetes Care Mission',
    category: 'eye_vision',
    campDate: '2026-08-22',
    startTime: '10:00',
    endTime: '16:00',
    venueName: 'Bally Citizen Welfare Centre',
    locationAddress: 'Bally Bazar, GT Road, Howrah',
    villageOrPanchayat: 'Bally Municipality Ward 14',
    district: 'Howrah',
    assignedDoctorIds: ['doc_004'],
    assignedDoctorNames: ['Dr. Joydeep Chatterjee (MS Ophthalmology)'],
    coordinatorName: 'Debabrata Pal',
    coordinatorPhone: '+91 98309 88122',
    targetBeneficiaries: 100,
    registeredCount: 96,
    attendedCount: 96,
    testsConductedCount: 192,
    freeCardsIssuedCount: 64,
    allocatedBudget: 18000,
    actualSpent: 17400,
    status: 'completed',
    freeServicesOffered: [
      'Visual Acuity & Refraction',
      'Slit Lamp Cataract Grading',
      'Intraocular Pressure (IOP)',
      'Fundus Examination',
      'Free Reading Spectacles',
      'Subsidized Phaco Surgery Referral'
    ],
    summaryNotes: '18 seniors diagnosed with operable cataracts. Scheduled for 100% sponsored micro-incision cataract surgery at base hospital.',
    createdAt: '2026-08-10T11:00:00.000Z',
    updatedAt: '2026-08-23T16:30:00.000Z'
  },
  {
    id: 'camp_sundarban_2026_03',
    campCode: 'CAMP-2026-090',
    title: 'Sundarbans Coastal Maternal, Pediatric & Anemia Screening Drive',
    ngoPartnerId: 'ngo_bharat_seva',
    ngoPartnerName: 'Bharat Arogya Seva Mission (Maternal & Child Relief)',
    category: 'pediatric_maternal',
    campDate: '2026-09-18',
    startTime: '08:30',
    endTime: '16:30',
    venueName: 'Gosaba Island Primary Health Centre Compound',
    locationAddress: 'Gosaba Main Ghat, Sundarbans',
    villageOrPanchayat: 'Gosaba Gram Panchayat',
    district: 'South 24 Parganas',
    assignedDoctorIds: ['doc_003'],
    assignedDoctorNames: ['Dr. Ananya Banerjee (MD Pediatric & Child Health)'],
    coordinatorName: 'Bikash Mondal',
    coordinatorPhone: '+91 98322 77112',
    targetBeneficiaries: 200,
    registeredCount: 65,
    attendedCount: 0,
    testsConductedCount: 0,
    freeCardsIssuedCount: 0,
    allocatedBudget: 35000,
    actualSpent: 0,
    status: 'scheduled',
    freeServicesOffered: [
      'Hemoglobin (Hb%) Finger-prick',
      'Pediatric Growth & Stunting Charting',
      'Maternal Prenatal Vitals Check',
      'Blood Grouping & Typing',
      'Iron & Folic Acid Syrup Distribution',
      'Deworming & Nutrition Kits'
    ],
    summaryNotes: 'Advance logistics coordinated with local boat transport and ASHA workers.',
    createdAt: '2026-08-25T14:00:00.000Z',
    updatedAt: '2026-08-30T10:00:00.000Z'
  }
];

export const DEFAULT_CAMP_ATTENDEES: CampAttendee[] = [
  {
    id: 'att_001',
    campId: 'camp_sonarpur_2026_01',
    campCode: 'CAMP-2026-081',
    tokenNumber: 'T-001',
    fullName: 'Haradhan Mondal',
    age: 58,
    gender: 'male',
    phone: '9831100221',
    villageOrLocality: 'Sonarpur Village West',
    vitals: {
      bpSystolic: 154,
      bpDiastolic: 96,
      bloodSugar: 224,
      spo2: 97,
      pulseRate: 82,
      weightKg: 64,
      heightCm: 165,
      bmi: '23.5'
    },
    prescribedTests: ['HbA1c Glycated Hemoglobin', 'Lipid Profile Screen', 'Serum Creatinine'],
    doctorObservations: 'Uncontrolled diabetes mellitus with Grade I hypertension. Started on Telmisartan 40mg + Metformin 500mg. Recommended low sodium diet.',
    freeMedicinesDispensed: 'Tab Metformin 500mg (1 Month), Tab Telmisartan 40mg (1 Month)',
    healthCardIssued: true,
    cardNumber: 'ROTARY-SEVA-2026-0041',
    subsidyAmount: 850,
    registeredAt: '2026-08-30T09:15:00.000Z',
    status: 'investigated'
  },
  {
    id: 'att_002',
    campId: 'camp_sonarpur_2026_01',
    campCode: 'CAMP-2026-081',
    tokenNumber: 'T-002',
    fullName: 'Parul Bala Das',
    age: 64,
    gender: 'female',
    phone: '9831100222',
    villageOrLocality: 'Kheyadaha Ward 2',
    vitals: {
      bpSystolic: 130,
      bpDiastolic: 80,
      bloodSugar: 142,
      spo2: 98,
      pulseRate: 74,
      weightKg: 52,
      heightCm: 150,
      bmi: '23.1'
    },
    prescribedTests: ['12-Lead Electrocardiogram (ECG)', 'Urine Routine Examination'],
    doctorObservations: 'Mild borderline fasting glucose. ECG normal sinus rhythm. Joint pain in bilateral knees.',
    freeMedicinesDispensed: 'Tab Calcium + Vit D3, Paracetamol SOS',
    healthCardIssued: true,
    cardNumber: 'ROTARY-SEVA-2026-0042',
    subsidyAmount: 600,
    registeredAt: '2026-08-30T09:22:00.000Z',
    status: 'prescribed'
  },
  {
    id: 'att_003',
    campId: 'camp_sonarpur_2026_01',
    campCode: 'CAMP-2026-081',
    tokenNumber: 'T-003',
    fullName: 'Subal Chandra Naskar',
    age: 49,
    gender: 'male',
    phone: '9831100223',
    villageOrLocality: 'Mahamayatala Colony',
    vitals: {
      bpSystolic: 120,
      bpDiastolic: 78,
      bloodSugar: 110,
      spo2: 99,
      pulseRate: 72,
      weightKg: 70,
      heightCm: 172,
      bmi: '23.7'
    },
    prescribedTests: ['Routine Health Checkup Panel'],
    doctorObservations: 'Healthy vitals. General wellness counseling provided.',
    freeMedicinesDispensed: 'Multivitamin capsules',
    healthCardIssued: true,
    cardNumber: 'ROTARY-SEVA-2026-0043',
    subsidyAmount: 400,
    registeredAt: '2026-08-30T09:35:00.000Z',
    status: 'screened'
  }
];

export const DEFAULT_CHARITY_GRANTS: CharityGrant[] = [
  {
    id: 'grant_2026_001',
    grantNumber: 'GRANT-2026-0041',
    patientId: 'pat_001',
    patientName: 'Ramesh Sardar',
    patientPhone: '+91 98300 12345',
    bplOrAadhaar: 'BPL-WB-772190-SOUTH24',
    ngoPartnerId: 'ngo_tata_csr',
    ngoPartnerName: 'Tata Corporate CSR Social Health & Oncology Aid Trust',
    medicalCaseTitle: '100% Subsidized Renal Dialysis & Comprehensive Nephrology Lab Panel',
    category: 'dialysis_subsidy',
    estimatedTotalBill: 16500,
    subsidyPercent: 100,
    approvedGrantAmount: 16500,
    approvalStatus: 'approved',
    approvedBy: 'Dr. Labmedix Super Admin & CSR Committee',
    approvalDate: '2026-08-28',
    disbursementDate: '2026-08-28',
    justification: 'Patient is a daily wage earner with End-Stage Renal Disease (ESRD). Income < ₹5,000/month. Verified BPL card holder.',
    voucherId: 'vch_grant_8821',
    notes: 'Approved under Tata CSR Critical Dialysis Pool.',
    createdAt: '2026-08-28T10:00:00.000Z',
    updatedAt: '2026-08-28T12:00:00.000Z'
  },
  {
    id: 'grant_2026_002',
    grantNumber: 'GRANT-2026-0042',
    patientId: 'pat_002',
    patientName: 'Amina Khatun Bibi',
    patientPhone: '+91 98300 23456',
    bplOrAadhaar: 'UID-9912-4412-1102',
    ngoPartnerId: 'ngo_rotary_3291',
    ngoPartnerName: 'Rotary Club Healthcare & Rural Relief Foundation',
    medicalCaseTitle: 'Full Cardiac Echocardiography, Doppler & Holter 24Hr Aid',
    category: 'bpl_relief',
    estimatedTotalBill: 8500,
    subsidyPercent: 100,
    approvedGrantAmount: 8500,
    approvalStatus: 'disbursed',
    approvedBy: 'Dr. Subhashish Roy (MD Cardiology)',
    approvalDate: '2026-08-25',
    disbursementDate: '2026-08-26',
    justification: 'Suspected severe mitral stenosis in low income widow. Immediate echo required before valve replacement referral.',
    notes: 'Grant settled against Rotary Healthcare Pool.',
    createdAt: '2026-08-25T14:30:00.000Z',
    updatedAt: '2026-08-26T11:00:00.000Z'
  },
  {
    id: 'grant_2026_003',
    grantNumber: 'GRANT-2026-0043',
    patientId: 'pat_003',
    patientName: 'Master Rahul Mondal (Age 9)',
    patientPhone: '+91 98300 34567',
    bplOrAadhaar: 'BPL-WB-88123-BARUIPUR',
    ngoPartnerId: 'ngo_bharat_seva',
    ngoPartnerName: 'Bharat Arogya Seva Mission (Maternal & Child Relief)',
    medicalCaseTitle: 'Pediatric Bone Marrow & Leukemia Diagnostic Profile',
    category: 'cancer_care',
    estimatedTotalBill: 22000,
    subsidyPercent: 100,
    approvedGrantAmount: 22000,
    approvalStatus: 'approved',
    approvedBy: 'Operations Administrator',
    approvalDate: '2026-08-29',
    justification: 'Severe refractory anemia and thrombocytopenia in 9-year-old child from rural BPL family.',
    notes: 'Expedited processing approved by Bharat Arogya Seva Mission.',
    createdAt: '2026-08-29T09:00:00.000Z',
    updatedAt: '2026-08-29T10:30:00.000Z'
  }
];

export const DEFAULT_NGO_FUND_TRANSACTIONS: NgoFundTransaction[] = [
  {
    id: 'ngotx_001',
    receiptNumber: '80G-REC-2025-001',
    ngoPartnerId: 'ngo_tata_csr',
    ngoPartnerName: 'Tata Corporate CSR Social Health & Oncology Aid Trust',
    type: 'deposit',
    amount: 600000,
    paymentMethod: 'neft_rtgs',
    referenceNumber: 'TATA-CSR-NEFT-8891024',
    date: '2025-02-10',
    purpose: 'Initial CSR Annual Grant Deposit for BPL Critical Care & Oncology Diagnostics',
    taxExemption80GIssued: true,
    balanceAfter: 600000,
    recordedBy: 'Dr. Labmedix Super Admin',
    createdAt: '2025-02-10T11:30:00.000Z'
  },
  {
    id: 'ngotx_002',
    receiptNumber: '80G-REC-2025-002',
    ngoPartnerId: 'ngo_rotary_3291',
    ngoPartnerName: 'Rotary Club Healthcare & Rural Relief Foundation',
    type: 'deposit',
    amount: 350000,
    paymentMethod: 'bank_transfer',
    referenceNumber: 'ROT-TRF-5541092',
    date: '2025-01-15',
    purpose: 'Rotary District 3291 Rural Health Camp Corpus & Emergency Patient Relief Fund',
    taxExemption80GIssued: true,
    balanceAfter: 350000,
    recordedBy: 'Dr. Labmedix Super Admin',
    createdAt: '2025-01-15T10:00:00.000Z'
  },
  {
    id: 'ngotx_003',
    receiptNumber: '80G-REC-2025-003',
    ngoPartnerId: 'ngo_lions_greater',
    ngoPartnerName: 'Lions Club International Eye & Diabetes Care Mission',
    type: 'deposit',
    amount: 250000,
    paymentMethod: 'cheque',
    referenceNumber: 'CHQ-LIONS-009941',
    date: '2025-03-01',
    purpose: 'Lions Vision First Campaign corpus for Senior Citizen Eye Screening & Cataract aid',
    taxExemption80GIssued: true,
    balanceAfter: 250000,
    recordedBy: 'Operations Administrator',
    createdAt: '2025-03-01T11:00:00.000Z'
  },
  {
    id: 'ngotx_004',
    receiptNumber: '80G-REC-2025-004',
    ngoPartnerId: 'ngo_bharat_seva',
    ngoPartnerName: 'Bharat Arogya Seva Mission (Maternal & Child Relief)',
    type: 'deposit',
    amount: 200000,
    paymentMethod: 'upi_csr',
    referenceNumber: 'UPI-BHARAT-20250401-884',
    date: '2025-04-01',
    purpose: 'Maternal Nutrition & Pediatric Blood Screening Pool Grant',
    taxExemption80GIssued: true,
    balanceAfter: 200000,
    recordedBy: 'Operations Administrator',
    createdAt: '2025-04-01T09:00:00.000Z'
  },
  {
    id: 'ngotx_005',
    receiptNumber: 'DISB-2026-081',
    ngoPartnerId: 'ngo_tata_csr',
    ngoPartnerName: 'Tata Corporate CSR Social Health & Oncology Aid Trust',
    type: 'grant_disbursement',
    amount: 16500,
    paymentMethod: 'grant_allocation',
    referenceNumber: 'GRANT-2026-0041',
    date: '2026-08-28',
    purpose: 'Grant settlement for patient Ramesh Sardar (Renal Dialysis & Nephrology Lab Panel)',
    taxExemption80GIssued: false,
    balanceAfter: 415000,
    recordedBy: 'Dr. Labmedix Super Admin',
    createdAt: '2026-08-28T12:00:00.000Z'
  },
  {
    id: 'ngotx_006',
    receiptNumber: 'DISB-2026-082',
    ngoPartnerId: 'ngo_rotary_3291',
    ngoPartnerName: 'Rotary Club Healthcare & Rural Relief Foundation',
    type: 'camp_expense',
    amount: 21800,
    paymentMethod: 'grant_allocation',
    referenceNumber: 'CAMP-2026-081',
    date: '2026-08-30',
    purpose: 'Expenditure allocation for Sonarpur Rural Diabetic & Cardiac Screening Camp',
    taxExemption80GIssued: false,
    balanceAfter: 241500,
    recordedBy: 'Operations Administrator',
    createdAt: '2026-08-30T10:00:00.000Z'
  }
];
